#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     colorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    clawServo,            tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    armServo,             tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"//

void initializeRobot()//this funcion will set the servos at a starting point at the beginning of the program,
//so we know where they start
{
	servo[clawServo] = 75;//set the claw to the open position at the beginning of the program
	servo[armServo] = 75;//set the arm about in the middle
	return;//return nothing, since this funtion is void
}//close function

task main()
{
	initializeRobot();//run funtion, see line 19
	while (true)//loop forever
	{
		getJoystickSettings(joystick);//update input info from joysticks
		if(joystick.joy1_y2 > -15 && joystick.joy1_y2 < 15)//if the joystick is near center power, which is 0
		{
			motor[leftMotor] = 0;//give 0% power to leftMotor
		}
		else//otherwise...
		{
			motor[leftMotor] = joystick.joy1_y2/2;//...power is half of the joystick value
		}


		if(joystick.joy1_y1 > -15 && joystick.joy1_y1 < 15)//if the joystick is near center power, which is 0
		{
			motor[rightMotor] = 0;//give rightMotor 0% power
		}
		else//otherwise...
		{
			motor[rightMotor] = joystick.joy1_y1/2;//...power is half of the joystick value
		}

		if(joy1Btn(1) == 1){//if the blue button (button 1) is pressed
			motor[leftMotor] = 50;//give 50% power to leftMotor
			motor[rightMotor] = 50;//give 50% power to rightMotor
		}

	}//end while
}
