#pragma config(Motor,  motorA,          rightDrive,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftDrive,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  if(abs(joystick.joy1_y1) < 15){
	  	motor[rightDrive] = 0;
	  }
	  else{
	  	motor[rightDrive] = 75;
	  }
	  if(abs(joystick.joy1_y2) < 15){
	  	motor[leftDrive] = 0;
	  }
	  else{
	  	motor[leftDrive] = 75;
	  }

	  if(joy1Btn(7) == 1){
	  	motor[arm] = 50;
	  }
	  else if(joy1Btn(8) == 1){
	  	motor[arm] = -50;
	  }
	  else{
	  	motor[arm] = 0;
	  }

  }//end of while
}//end task main
