#pragma config(Motor,  motorA,          rightDrive,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftDrive,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          arm,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  if(abs(joystick.joy1_y1) < 15){
	  	motor[rightDrive] = 0;
	  }
	  else{
	  	motor[rightDrive] = 75;
	  }
	  if(abs(joystick.joy1_y2) < 15){
	  	motor[leftDrive] = 0;
	  }
	  else{
	  	motor[leftDrive] = 75;
	  }

	  if(joy1Btn(7) == 1){
	  	motor[arm] = 50;
	  }
	  else if(joy1Btn(8) == 1){
	  	motor[arm] = -50;
	  }
	  else{
	  	motor[arm] = 0;
	  }

  }//end of while
}//end task main
