#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     colorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    clawServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    armServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"//include the file that has all of the joystick and button functions
#include "hitechnic-irseeker-v2.h"//include Xander's IR driver
#include "constants.h"
#include "autonomous.h"


void initializeRobot()//this funcion will set the servos at a starting point at the beginning of the program,
//so we know where they start
{
	servo[clawServo] = CLAW_SERVO_INIT;//set the claw to the open position at the beginning of the program
	servo[armServo] = ARM_SERVO_INIT;//set the arm about in the middle
	return;//return nothing, since this funtion is void
}//close function

task main()//start task main
{
	initializeRobot();//run funtion, see line 19
	while (true)//loop forever
	{
		getJoystickSettings(joystick);//update input info from joysticks
		if(joystick.joy1_y2 > -JOYSTICK_LIMIT && joystick.joy1_y2 < JOYSTICK_LIMIT)//if the joystick is near center power, which is 0
		{
			motor[leftMotor] = 0;//give 0% power to leftMotor
		}
		else//otherwise...
		{
			motor[leftMotor] = joystick.joy1_y2/MOTOR_POWER_DIVIDER;//...power is half of the joystick value
		}


		if(joystick.joy1_y1 > -JOYSTICK_LIMIT && joystick.joy1_y1 < JOYSTICK_LIMIT)//if the joystick is near center power, which is 0
		{
			motor[rightMotor] = 0;//give rightMotor 0% power
		}
		else//otherwise...
		{
			motor[rightMotor] = joystick.joy1_y1/MOTOR_POWER_DIVIDER;//...power is half of the joystick value
		}

		if(joy1Btn(1) == 1){//if the blue button (button 1) is pressed
			motor[leftMotor] = 50;//give 50% power to leftMotor
			motor[rightMotor] = 50;//give 50% power to rightMotor
		}

		if(joy1Btn(6) == 1) {//if the right top back button (button 9) is pressed
			servo(armServo) = ARM_UP;//put the arm servo at position 20 (up)
		}
		else if(joy1Btn(8) == 1) {//if the right bottom button (button 8) is pressed
			servo(armServo) = ARM_DOWN;//put the arm servo at position 195 (down)
		}

		if(joy1Btn(5) == 1 && servo(armServo) < CLAW_HIGH_LIMIT) {//if the left top back button (button 5) is pressed and claw is not already fully open
			servo(clawServo) -= 0.1;//open the claw
		}
		else if(joy1Btn(7) == 1 && servo(armServo) > CLAW_LOW_LIMIT) {//if the left bottom button (button 7) is pressed and claw is not already fully closed
			servo(clawServo) += 0.1;//close the claw
		}

		if(joy1Btn(3) == 1) {
			runAutonomous();
		}

	}//end while
}//end task main
