#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     colorSensor,    sensorColorNxtFULL)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor2,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"//include the file that has all of the joystick and button functions
#include "hitechnic-irseeker-v2.h"//include Xander's IR driver
#include "constants.h"


void initializeRobot()//this funcion will set the servos at a starting point at the beginning of the program,
//so we know where they start
{

	return;
}

task main()//start task main
{
	initializeRobot();//run funtion, see line 19
	while (true)//loop forever
	{
		getJoystickSettings(joystick);//update input info from joysticks
		if(joystick.joy1_y2 > -JOYSTICK_LIMIT && joystick.joy1_y2 < JOYSTICK_LIMIT)//if the joystick is near center power, which is 0
		{
			motor[leftMotor] = 0;//give 0% power to leftMotor
			motor[leftMotor2] = 0;
		}
		else//otherwise...
		{
			motor[leftMotor] = joystick.joy1_y2;
			motor[leftMotor2] = joystick.joy1_y2;
		}


		if(joystick.joy1_y1 > -JOYSTICK_LIMIT && joystick.joy1_y1 < JOYSTICK_LIMIT)//if the joystick is near center power, which is 0
		{
			motor[rightMotor] = 0;//give rightMotor 0% power
			motor[rightMotor2] = 0;
		}
		else//otherwise...
		{
			motor[rightMotor] = joystick.joy1_y1;
			motor[rightMotor2] = joystick.joy1_y1;
		}

		if(joy1Btn(1) == 1){//if the blue button (button 1) is pressed
			motor[leftMotor] = 50;//give 50% power to leftMotor
			motor[leftMotor2] = 50;
			motor[rightMotor] = 50; //give 50% power to rightMotor
			motor[rightMotor2] = 50;
		}


	}//end while
}//end task main
